### ISSUE TITLE
key value mapping doesn't work when the key is 'int'

### ISSUE THREAD

**Issue by marcelomatus** [beached/daw_json_link#361]
This one doesn't compile

json_key_value < "f1", std::unordered_map < int, double> >

This one is ok

json_key_value < "f1", std::unordered_map < std::string, double > >

This one also compiles

json_key_value_array < "f1", std::unordered_map < int, double> >

**Comment by beached** [comment]
The error isn't the best there, ill add a todo for that, but it is because `json_key_value` parses to/from json classes https://github.com/beached/daw_json_link/blob/release/docs/cookbook/key_values.md#as-class So the key type must be a string. bool/numbers can be used if they set the option flag for it. 

```cpp
using type = json_member_list<json_key_value<
		  kv, std::unordered_map<int, double>, double,
		  json_number_no_name<int, options::number_opt(options::LiteralAsStringOpt::Always )>>>;
```

This is probably what you want.  And would map to data like 

```json
{
  "123": 1.234,
  "545": 3.14159
}
```

I think I am going to change this to default to just work in the future and set the option automatically in this context instead of a better error. It cannot work any other way anyways.

Thanks again

**Comment by beached** [comment]
```cpp
using type = json_member_list<json_key_value<"kv", std::unordered_map<int, double>>
```

 should work once this goes through.  It will force the encoding to be strings for numbers/bool when used as key type.  Good idea, this was acknowledged in the docs but I just didn't think to add a feature for this.

**Comment by beached** [comment]
https://github.com/beached/daw_json_link/releases/tag/v3.11.0
