### ISSUE TITLE
Seeking Advice: implementing MsgPack deserialization

### ISSUE THREAD

**Issue by cyanidle** [beached/daw_json_link#412]
Hello. I am maintaining a JSON-RPC library for my company. I would really like to switch from nlohmann to this library (in the research stage currently). I am interested in somehow implementing deserialization logic for msgpack (to be more effective about numbers parsing and msg sizes). Is there a way to do this here? 

Maybe somehow implement a parsing layer to accept different data format and emit sax events. If possible, how should I do it? I should mention I have no knowledge about this library whatsoever for now)

**Comment by beached** [comment]
At this point the abstractions are too coupled to JSON to be effective at msgpack.  However one thing to keep in mind is that strings are going to be about the same size across serialization formats and that one can use arrays in JSON to represent classes as they are ordered and do not need to be homogenous.  So instead of 

```json
{"member0": 1234.5,"member1": true,"member2":"Hello World"}
```

one can serialize it as 

```json
[1234.5,true,"Hello World"]
```
